### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by aureliosaraiva** [ember-brasil/website#1]
https://github.com/EmberJSBrasil/ember-guides/tree/master/source/getting-started

- [x] core-concepts.md
- [x] index.md
- [x] quick-start.md

**Comment by danilovaz** [comment]
@aureliosaraiva vou pegar esse aqui para traduzir :+1:

**Comment by aureliosaraiva** [comment]
@danilovaz Perfeito.

Talves isso pode te ajudar, já tem algumas coisas traduzidas no guides, antes do projeto morrer.

https://github.com/emberjs/guides/tree/e39f8513cfdb2f761af628e7b52f0eafb2335a2d/source/localizable/getting-started

**Comment by danilovaz** [comment]
@aureliosaraiva Beleza, posso reaproveitar o que já estiver sido traduzido.

**Comment by aureliosaraiva** [comment]
@danilovaz Abre um PR com as alterações, vou abrir PR com as minhas também pra gente se auto revisar.

Além disso, agora ta rolando o travis que está validando varias coisas de caminho de image e links corretos.

**Comment by danilovaz** [comment]
Finalizado com o PR #18
