### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by aureliosaraiva** [ember-brasil/website#14]
https://github.com/ember-brasil/website/tree/master/source/glossary

**Comment by aureliosaraiva** [comment]
Tem essa tradução anterior que pode ser usada como base.

https://github.com/emberjs/guides/blob/e39f8513cfdb2f761af628e7b52f0eafb2335a2d/source/localizable/glossary/web-development.pt-BR.md

**Comment by marceloboth** [comment]
@aureliosaraiva eu finalizo isso 👍

**Comment by aureliosaraiva** [comment]
@marceloboth Legal!! Quando abrir o PR referencia essa issue.

Vou colocar você como responsável por essa parte.

**Comment by danilovaz** [comment]
Done with #54
