### ISSUE TITLE
Contributing to Ember.js / Repositories

### ISSUE THREAD

**Issue by aureliosaraiva** [ember-brasil/website#15]
https://github.com/ember-brasil/website/blob/master/source/contributing/repositories.md

**Comment by aureliosaraiva** [comment]
Tem a tradução anterior que pode ser usada como base:

https://github.com/emberjs/guides/blob/e39f8513cfdb2f761af628e7b52f0eafb2335a2d/source/localizable/contributing/repositories.pt-BR.md

**Comment by rahhrta** [comment]
@aureliosaraiva @danilovaz posso fazer esse?

**Comment by aureliosaraiva** [comment]
Você pode sim, se tiver dúvida estou a sua disposição.

**Comment by aureliosaraiva** [comment]
Aqui tem informações que pode te ajudar.
https://github.com/ember-brasil/website/blob/master/CONTRIBUTING.md

@rahhrta
