### ISSUE TITLE
Página inicial do guia

### ISSUE THREAD

**Issue by aureliosaraiva** [ember-brasil/website#41]
https://github.com/ember-brasil/website/blob/master/source/guides/index.md

**Comment by lucasaugustofrontend** [comment]
Eu poderia fazer essa tradução?

**Comment by aureliosaraiva** [comment]
@lucasaugustofrontend perfeito, pode fazer sim. Vou coloca-lo como responsável.

Obrigado!

**Comment by lucasaugustofrontend** [comment]
o que precisa ser feito nessa parte exatamente?

**Comment by aureliosaraiva** [comment]
Apenas traduzir  o conteúdo.

**Comment by lucasaugustofrontend** [comment]
Então eu preciso entra na página de started  Begin do ember  é traduzir essa parte correto?

Caso eu esteja errado poderia me passa o link da página?
